### ISSUE TITLE
Inconsitency between maptiler cloud style and map provided by MapTiler QGIS plugin

### ISSUE THREAD

**Issue by mlerjen** [maptiler/qgis-maptiler-plugin#143]
**What do I do?**
I define a map style by the MapTiler cloud style editor. As I am interested in differentiating path, tracks and roads I define them separately. e.g. name: Tracks  source: OpenMapTiles; layer:Transportation Filter:  class == track.

![image](https://user-images.githubusercontent.com/15611653/102498914-dc3b6580-407a-11eb-9ddc-f120861e4d2b.png)

As far it works. Now: publishing the style; importing it by the MapTiler QGIS plugin.

**What happens?**
![image](https://user-images.githubusercontent.com/15611653/102499476-84512e80-407b-11eb-99c2-48a77fce5c54.png)
-> The different styles of the highway network is missing, not found at all in the symbology
-> Confirming issue #139 

**What should happen instead?**
The results of the MapTiler cloud style editor and the QGIS vector map should be consistent.

**Comment by lazaa32** [comment]
Hi @mlerjen 
the plugin converts style definition in style.json from GL library syntax into QGIS symbology syntax. Not everything can be converted though. E.g. if your style.json has properties defined using expressions QGIS is having problem to convert it.
Missing labels on contours lines is a known issue and hopefully it will be fixed in next version of the plugin.
